package events

var ALL_EVENT_NAMES = []string{
	COLLISON_EVENT_NAME,
	MOVEMENT_REQUESTMOVE_EVENT_NAME,
	MOVEMENT_COMPLETED_EVENT_NAME,
	//MOVEMENT_STEP_EVENT_NAME, too many...
	ABILITY_REQUESTUSE_EVENT_NAME,
	SELECTION_SELECTED_EVENT_NAME,
	SELECTION_DESELECTED_EVENT_NAME,
	INPUT_SELECT_EVENT_NAME,
	INPUT_INTERACT_EVENT_NAME,
	INPUT_CREATEUNIT_EVENT_NAME,
	UNIT_REQUEST_DAMAGE_EVENT,
	UNIT_DEATH_EVENT,
	ABILITY_REQUESTUSE_EVENT_NAME,
	ABILITY_COMPLETED_EVENT_NAME,
	ABILITY_ABORT_EVENT_NAME,
	UNIT_ATTRIBUTE_CHANGE_EVENT,
	LOOT_REQUEST_SPAWN_EVENT,
	LOOT_REQUEST_PICKUP_EVENT,
}

// TODO make this part of the eventmanager
func InitEventCapturing(channel chan<- BaseEvent) {

	for _, eventName := range ALL_EVENT_NAMES {
		Mailbox.PriorityListen(eventName, func(msg BaseEvent) {
			channel <- msg
		})
	}

}
